# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 32c5384c18ced67c8f5d2d8904b75ebade4c3aa28a3a0352afa632a43e1d3b534d6e20819ecb2c0807ca0fd541de38ab5381f184290a0d3880c2a3439756021c

test:
  secret_key_base: a35bf3fe531c5e65465f743935497da1cc6f9a584507832d5161dd4bd7fdc90277f76998d47d395890c86546dfca01a57be043137d40f7529b5015be8381b8f2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
